import requests
import smtplib


MY_LAT="Your Location LATITUDE"
MY_LANG="Your longitude LANGITUDE"
api_key = "Your open weather API"
parameters = {
    "lat":MY_LAT,
    "lon":MY_LANG,
    "appid":api_key,
    "cnt" : 4
}

response = requests.get("https://api.openweathermap.org/data/2.5/forecast", params=parameters)
response.raise_for_status()
weather_data = response.json()

will_rain = False
for hour_data in weather_data['list']:
    conditional_code = (hour_data["weather"][0]['id'])
    if int(conditional_code) < 700:
        will_rain= True
if will_rain:
    
    email = "Enter Your Email"
    pass_key = "Enter App Password generated by gmail"
    connection = smtplib.SMTP("Your mail provider SMTP")

    connection.starttls()
    connection.login(user=email, password=pass_key)
    connection.sendmail(from_addr=email, to_addrs="your address", msg="Subject:Rain Alert\n\nIt's About to rain so Please bring Umbrella.")
    connection.close()